project:
  type: website

website:
  title: "Tom Parry"
  site-url: "https://tomwparry.github.io"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo